general {
    lock_cmd = pidof quickshell || quickshell -p ~/.config/quickshell/lockscreen/shell.qml # avoid starting multiple quickshell instances.
    before_sleep_cmd = quickshell -p ~/.config/quickshell/lockscreen/shell.qml # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
    ignore_dbus_inhibit = false # listen to apps telling hypridle not to suspend
    ignore_systemd_inhibit = false
}

listener {
    timeout = 300                          # 5 min.
    on-timeout = systemctl suspend         # suspend.
}
