#!/usr/bin/env bash

# change colorschemes
wal -qnti "$1"

# set wallpaper
awww img -t none "$(< "${HOME}/.cache/wal/wal")"


#notify wallpaper and colorsheme change
notify-send "wallpaper and colorscheme changed."

